spring:
#  数据源配置
  datasource:
    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://114.242.60.27:5432/bpms
      username: wm
      password: wm123

#      本地
#      url: jdbc:postgresql://localhost/bpms
#      username: WM
#      password: WM123

#配置开发环境的运行端口
server:
  port: 8087

#用户头像设置
userphoto:
  server: localhost


# 其他配置
#    oracle:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@114.242.60.27:1521:orcl
#      username: chart/task/taskindex/deptchecklist
#      password: Oracle004
#    mysql:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/whwblog?useUnicode=true&characterEncoding=utf8&useSSL=false
#      username: whw
#      password: whw123

# redis配置
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    password: redis789
#    # 连接超时时间（毫秒）
#    timeout: 5000
#    lettuce:
#      pool:
#        max-active: 10 #最大连接数
#        max-wait: 2000  #最大等待毫秒
#        max-idle: 20  #最大空闲数
#        min-idle: 5 #最小空闲数

#缓存配置
#  cache:
#    type: redis
#    cache-names: wmRedisCache
